# see ci.yml for completed(?) file
trigger:
  - azure-pipelines
  - master

jobs:
  - job: Ubuntu_unit_test
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - script: echo "Hello World!!!"
        displayName: Hello_world