# see ci.yml for completed(?) file
trigger:
  - azure-pipelines
  - master

jobs:
  - job: Ubuntu_unit_test
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        displayName: 'Get python version $(python.version)'
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
      
      - script: python -m pip install --upgrade pip
        displayName: 'upgrade pip'
      
      - script: |
          pip install -r requirements.txt
        displayName: 'install dependencies'

      - script: |
          python -m pip install pylint --quiet
          pylint boston/*.py
          pylint iris/*.py
        displayName: 'Run lint tests'
